import React from 'react'
import { Document, Page, Text, View, StyleSheet } from '@react-pdf/renderer'

const s = StyleSheet.create({
  page: { padding: 40, fontFamily: 'Helvetica', fontSize: 11, color: '#1a1a1a' },
  header: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 24, paddingBottom: 12, borderBottomWidth: 2, borderBottomColor: '#e5e5e5' },
  brand: { fontSize: 18, fontWeight: 'bold' },
  url: { fontSize: 10, color: '#666', textAlign: 'right' },
  scoreBox: { alignItems: 'center', marginVertical: 24 },
  score: { fontSize: 48, fontWeight: 'bold' },
  grade: { fontSize: 24, fontWeight: 'bold', marginTop: 4 },
  dimRow: { flexDirection: 'row', justifyContent: 'space-between', padding: '6 10', backgroundColor: '#f5f5f5', borderRadius: 4, marginBottom: 4 },
  dimLabel: { fontSize: 11, color: '#555' },
  dimScore: { fontSize: 11, fontWeight: 'bold' },
  h2: { fontSize: 14, fontWeight: 'bold', marginTop: 20, marginBottom: 8, color: '#333' },
  issue: { paddingVertical: 4, borderBottomWidth: 1, borderBottomColor: '#eee', fontSize: 10 },
  severity: { fontSize: 9, fontWeight: 'bold', marginRight: 4 },
  suggestion: { paddingVertical: 6, borderBottomWidth: 1, borderBottomColor: '#eee' },
  sugTitle: { fontSize: 11, fontWeight: 'bold' },
  sugFix: { fontSize: 10, color: '#666', marginTop: 2 },
  footer: { marginTop: 30, paddingTop: 12, borderTopWidth: 1, borderTopColor: '#e5e5e5', fontSize: 9, color: '#999', textAlign: 'center' },
})

interface Props {
  report: any
  brandName: string
  brandColor: string
}

export function ReportPdf({ report, brandName, brandColor }: Props) {
  const dims = [
    { label: 'Structure', score: report.structureScore },
    { label: 'Design', score: report.designScore },
    { label: 'Copy', score: report.copyScore },
    { label: 'Conversion', score: report.conversionScore },
    { label: 'Performance', score: report.performanceScore },
    { label: 'SEO', score: report.seoScore },
    { label: 'Benchmark', score: report.benchmarkScore },
  ]
  const issues = ((report.issues as any[]) || []).slice(0, 20)
  const suggestions = ((report.suggestions as any[]) || []).slice(0, 10)
  const gradeColor = report.letterGrade?.startsWith('A') ? '#22c55e' :
    report.letterGrade?.startsWith('B') ? '#eab308' : '#ef4444'

  return (
    <Document>
      <Page size="A4" style={s.page}>
        <View style={s.header}>
          <Text style={[s.brand, { color: brandColor }]}>{brandName || 'PageScore'}</Text>
          <Text style={s.url}>{report.url}{'\n'}{new Date(report.createdAt).toLocaleDateString()}</Text>
        </View>

        <View style={s.scoreBox}>
          <Text style={s.score}>{report.overallScore}</Text>
          <Text style={[s.grade, { color: gradeColor }]}>{report.letterGrade}</Text>
        </View>

        {dims.map(d => (
          <View key={d.label} style={s.dimRow}>
            <Text style={s.dimLabel}>{d.label}</Text>
            <Text style={s.dimScore}>{d.score ?? 'N/A'}</Text>
          </View>
        ))}

        {issues.length > 0 && (
          <>
            <Text style={s.h2}>Issues ({issues.length})</Text>
            {issues.map((i, idx) => (
              <Text key={idx} style={s.issue}>
                <Text style={s.severity}>[{i.severity}]</Text> {i.message}
              </Text>
            ))}
          </>
        )}

        {suggestions.length > 0 && (
          <>
            <Text style={s.h2}>AI Suggestions</Text>
            {suggestions.map((sg, idx) => (
              <View key={idx} style={s.suggestion}>
                <Text style={s.sugTitle}>{sg.title}</Text>
                <Text style={s.sugFix}>{sg.fix}</Text>
              </View>
            ))}
          </>
        )}

        <Text style={s.footer}>Generated by {brandName || 'PageScore'}</Text>
      </Page>
    </Document>
  )
}
