import { NextRequest, NextResponse } from 'next/server'
import { getServerSession } from 'next-auth'
import { prisma } from '@/lib/prisma'
import { checkPlanAccess } from '@/lib/plan-gating'

export async function GET(req: NextRequest, { params }: { params: Promise<{ id: string }> }) {
  const session = await getServerSession()
  const userId = (session?.user as any)?.id

  if (!userId) {
    return NextResponse.json({ error: 'Authentication required' }, { status: 401 })
  }

  const access = await checkPlanAccess(userId, 'pdf')
  if (!access.allowed) {
    return NextResponse.json({ error: access.reason }, { status: 403 })
  }

  const { id } = await params
  const report = await prisma.analysisReport.findUnique({ where: { id } })
  if (!report) {
    return NextResponse.json({ error: 'Report not found' }, { status: 404 })
  }

  // Build a simple HTML-based PDF using the report data
  const dimensions = [
    { label: 'Structure', score: report.structureScore },
    { label: 'Design', score: report.designScore },
    { label: 'Copy', score: report.copyScore },
    { label: 'Conversion', score: report.conversionScore },
    { label: 'Performance', score: report.performanceScore },
    { label: 'SEO', score: report.seoScore },
    { label: 'Benchmark', score: report.benchmarkScore },
  ]

  const issues = (report.issues as any[]) || []
  const suggestions = (report.suggestions as any[]) || []

  const gradeColor = report.letterGrade.startsWith('A') ? '#22c55e' :
    report.letterGrade.startsWith('B') ? '#eab308' : '#ef4444'

  const html = `<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<style>
  * { margin: 0; padding: 0; box-sizing: border-box; }
  body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; color: #1a1a1a; padding: 40px; max-width: 800px; margin: 0 auto; }
  .header { display: flex; justify-content: space-between; align-items: center; margin-bottom: 32px; padding-bottom: 16px; border-bottom: 2px solid #e5e5e5; }
  .logo { font-size: 20px; font-weight: 700; color: #0ea5e9; }
  .url { font-size: 12px; color: #666; }
  .score-section { text-align: center; margin: 32px 0; }
  .score { font-size: 64px; font-weight: 800; }
  .grade { font-size: 32px; font-weight: 700; color: ${gradeColor}; }
  .dimensions { display: grid; grid-template-columns: 1fr 1fr; gap: 12px; margin: 24px 0; }
  .dim { display: flex; justify-content: space-between; padding: 8px 12px; background: #f5f5f5; border-radius: 6px; }
  .dim-label { font-size: 13px; color: #555; }
  .dim-score { font-size: 13px; font-weight: 600; }
  h2 { font-size: 16px; margin: 24px 0 12px; color: #333; }
  .issue { padding: 8px 0; border-bottom: 1px solid #eee; font-size: 13px; }
  .issue-severity { display: inline-block; padding: 1px 6px; border-radius: 3px; font-size: 11px; font-weight: 600; margin-right: 6px; }
  .high { background: #fecaca; color: #991b1b; }
  .medium { background: #fef3c7; color: #92400e; }
  .low { background: #e0f2fe; color: #075985; }
  .suggestion { padding: 10px 0; border-bottom: 1px solid #eee; }
  .suggestion-title { font-size: 13px; font-weight: 600; }
  .suggestion-fix { font-size: 12px; color: #666; margin-top: 2px; }
  .footer { margin-top: 40px; padding-top: 16px; border-top: 1px solid #e5e5e5; font-size: 11px; color: #999; text-align: center; }
</style>
</head>
<body>
  <div class="header">
    <div class="logo">PageScore Report</div>
    <div class="url">${report.url}<br>${new Date(report.createdAt).toLocaleDateString()}</div>
  </div>
  <div class="score-section">
    <div class="score">${report.overallScore}</div>
    <div class="grade">${report.letterGrade}</div>
  </div>
  <div class="dimensions">
    ${dimensions.map(d => `<div class="dim"><span class="dim-label">${d.label}</span><span class="dim-score">${d.score}/100</span></div>`).join('')}
  </div>
  ${issues.length > 0 ? `<h2>Issues Found (${issues.length})</h2>${issues.slice(0, 20).map(i => `<div class="issue"><span class="issue-severity ${i.severity}">${i.severity}</span>${i.message}</div>`).join('')}` : ''}
  ${suggestions.length > 0 ? `<h2>AI Suggestions</h2>${suggestions.slice(0, 10).map(s => `<div class="suggestion"><div class="suggestion-title">${s.title}</div><div class="suggestion-fix">${s.fix}</div></div>`).join('')}` : ''}
  <div class="footer">Generated by PageScore &mdash; pagescore.app</div>
</body>
</html>`

  // Return HTML that can be printed to PDF by the browser
  return new NextResponse(html, {
    headers: {
      'Content-Type': 'text/html; charset=utf-8',
      'Content-Disposition': `inline; filename="pagescore-${report.letterGrade}-${report.overallScore}.html"`,
    },
  })
}
